@Restaurants.API_HostAddress = https://localhost:7238

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "T",
  "description": "A fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisineA fine dining restaurant offering international cuisine",
  "category": "sadfsadf",
  "hasDelivery": true,
  "contactNumber": "ddd",
  "contactEmail": "contact.com",
  "city": "Dubai",
  "street": "123 Sheikh Zayed Road",
  "postalCode": "12345"
}

###
GET https://localhost:7238/api/Restaurants/5

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  //CreateRestaurantDto
}

###
